### PR TITLE
Implemented the STEM Essay outline part

### PR DESCRIPTION
**Pull request by SimonLiu19**
By Shenghao Liu

### CODE REVIEW

**Comment by Dillettant** [comment]
LGTM. 

Nitpick: Could you move it to `src/outline_gen`?

**Comment by SimonLiu19** [comment]
Hi,

I just made the adjustments and can you confirm everything is correct now?
Thanks!

Best,
Simon

**Comment by Dillettant** [comment]
Hey Simon,

I don't see the open PR. Did you just close the issue?

Bests,
Eddie

**Comment by SimonLiu19** [comment]
Yes, I closed the pull request and created another folder and commit the
query directly, Does it look good?

**Comment by Dillettant** [comment]
[image: image.png]
I still don't see the new commit pushed to the master branch or PR.

**Comment by SimonLiu19** [comment]
Hi Eddie,

I think I was committing to another public repo under my github, would you
be able to check now? Thanks!

Best Regards,
Simon

**Comment by Dillettant** [comment]
LGTM. Merged.On Mar 4, 2024, at 5:02 PM, SimonLiu19 ***@***.***> wrote:﻿
Hi Eddie,



I think I was committing to another public repo under my github, would you

be able to check now? Thanks!



Best Regards,

Simon

**Comment by taylorcammack** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
talesa, @dev-techmoe, @damascopaul, @aleksandryessin, @walez, @cjdsellers, @sonkey, @ruyan768, @kingzez, @wphan, @sxp4u, @nhulong58, @Merlin153, @Earthson, @iswangjiaxing, @gh-interests2, @MelnikovAG, @TimvanScherpenzeel, @sephsa, @soulichanh040884, @SLigtvoet, @yitongseu, @glyphx, @TonyXhufi, @tensaix2j, @uname-yang, @midikang, @cgore, @fqdeng, @MRFORTUNE6, @SamuelSarle, @xulouzhe, @NullVoxPopuli, @jabbalaci, @Amr4crypto, @jvargas714, @bonetou, @arkii, @GmiSoft, @Nwvid, @maperez42, @Platinumwrist, @daveschumaker, @pauldevos, @PengLoveHONG, @JiuZhuYou, @alexz27, @qyvlik, @XinchenVincent, @dzh

**Pull request closed without merging**
